[package]
name = "bevy_jsn"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy.workspace = true
bevy_jsn_geometry = { path = "../bevy_jsn_geometry" }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror = "2"

[lints]
workspace = true
