[package]
name = "editor_feathers"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy.workspace = true
bevy_notify.workspace = true
bevy_ui_text_input.workspace = true
bevy_easings.workspace = true
editor_widgets.workspace = true
lucide-icons.workspace = true

[lints]
workspace = true
